language: node_js

cache:
  directories:
  - node_modules

node_js:
  - "6"

dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable
  firefox: "latest-esr"

before_install:
  - if [[ -n "${AAT_TOKEN}" ]]; then sed -e "s|\${AAT_TOKEN}|$AAT_TOKEN|g" < .aat.yml.src > .aat.yml; fi
  - tar -xjf /tmp/firefox-latest-esr.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm prune
  - npm install || (cat npm-debug.log; false)
  - if [[ -n "${AAT_TOKEN}" ]]; then npm i https://aat.mybluemix.net/dist/karma-ibma.tgz; fi

script:
  - yarn ci-check

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
